### PR TITLE
Sample for multi attribute logon support authenticator

### PR DESCRIPTION
**Pull request by GDRDABARERA**

### CODE REVIEW

**Comment by mefarazath** [comment]
@GDRDABARERA A quick question, are we using the new user core APIs[1] that support multi-attribute login in the sample?

or is this written as a generic sample to be valid for previous versions as well?


[1] https://github.com/wso2/carbon-kernel/blob/4.6.x/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/UniqueIDUserStoreManager.java#L54

**Comment by janakamarasena** [comment]
This is using the old JAVA APIs if I am not mistaken. @rksk please correct me if am wrong.

**Comment by rksk** [comment]
> This is using the old JAVA APIs if I am not mistaken. @rksk please correct me if am wrong.

Yes, this is the one we improved with regex.

**Comment by mefarazath** [comment]
I think @GDRDABARERA has mentioned this is applicable for up to 5.9.0

**Comment by GDRDABARERA** [comment]
@rksk will submit another PR with the upto date sample. Hence closing this PR

**Pull request closed without merging**
